ulimit = 2048

[port]
  jsonrpc = 8881
  websocket = 9991
  pprof = 53121
  monitor = 40011

[jsonrpc]
  gas_cap = 300000000
  evm_timeout = '5s'

  [jsonrpc.limiter]
    interval = '50ns'
    quantum = 500
    capacity = 10000

[p2p]
  security = 'tls'
  send_timeout = '5s'
  read_timeout = '5s'

  [p2p.ping]
    enable = false
    duration = '15s'

  [p2p.pipe]
    broadcast_type = 'simple'
    receive_msg_cache_size = 100

[order]
  type = 'rbft'

[ledger]
  kv = 'leveldb'

[executor]
  type = 'exec_native'

[genesis]
  chainid = 1356
  gas_limit = 100000000
  gas_price = 5000000000000
  max_gas_price = 10000000000000
  min_gas_price = 1000000000000
  gas_change_rate = 0.125
  balance = '1000000000000000000000000000'

[[genesis.admins]]
  address = '0xc7F999b83Af6DF9e67d0a37Ee7e900bF38b3D013'
  weight = 1
  name = 'King'

[[genesis.admins]]
  address = '0x79a1215469FaB6f9c63c1816b45183AD3624bE34'
  weight = 1
  name = 'Red'

[[genesis.admins]]
  address = '0x97c8B516D19edBf575D72a172Af7F418BE498C37'
  weight = 1
  name = 'Apple'

[[genesis.admins]]
  address = '0xc0Ff2e0b3189132D815b8eb325bE17285AC898f8'
  weight = 1
  name = 'Cat'

[[genesis.members]]
  node_id = '16Uiu2HAmJ38LwfY6pfgDWNvk3ypjcpEMSePNTE6Ma2NCLqjbZJSF'

[[genesis.members]]
  node_id = '16Uiu2HAmRypzJbdbUNYsCV2VVgv9UryYS5d7wejTJXT73mNLJ8AK'

[[genesis.members]]
  node_id = '16Uiu2HAmTwEET536QC9MZmYFp1NUshjRuaq5YSH1sLjW65WasvRk'

[[genesis.members]]
  node_id = '16Uiu2HAmQBFTnRr84M3xNhi3EcWmgZnnBsDgewk4sNtpA3smBsHJ'

[pprof]
  enbale = true
  ptype = 'http'
  mode = 'mem'
  duration = '30s'

[monitor]
  Enable = true

[log]
  level = 'info'
  filename = 'axiom.log'
  report_caller = false
  max_age = '2160h0m0s'
  rotation_time = '24h0m0s'

  [log.module]
    p2p = 'info'
    consensus = 'info'
    executor = 'info'
    router = 'info'
    api = 'info'
    coreapi = 'info'
    storage = 'info'
    profile = 'info'
    tss = 'info'
    finance = 'info'
