[timed_gen_block]
enable = false
no_tx_batch_timeout = '2s'

[limit]
enable = false
limit = 10000
burst = 10000

[mempool]
pool_size = 50000   # How many transactions could the txPool stores in total
batch_timeout = '500ms'     # Primary generate a batch, although batchsize isn't reached yet
batch_size = 500        # How many transactions should the primary pack when generating a batch
tolerance_time = '5m0s'     # The max tolerance time duration (in seconds) of out-of-date
tolerance_remove_time = '15m0s' # The max tolerance remove time duration (in seconds) of tx alive in mempool

[tx_cache]
set_size = 25               # How many transactions should the node broadcast at once
set_timeout = '100ms'       # Node broadcasts transactions if there are cached transactions, although set_size isn't reached ye


[rbft]
check_interval = '3m0s'     # interval of the check loop
vc_period = 0               # After how many checkpoint periods( Blocks = 10 * vcperiod ) the primary gets cycled automatically. ( Set 0 to disable )
checkpoint_period = 10      # The checkpoint period (in blocks)

    [rbft.timeout]
    sync_state = '3s'           # How long to wait quorum sync state response
    sync_interval = '1m0s'      # How long to restart sync state process
    recovery = '15s'            # How long to wait before recovery finished(This is for release1.2)
    first_request = '30s'       # How long to wait before first request should come
    request = '6s'              # How long may a request(transaction batch) take between reception and execution, must be greater than the batch timeout
    null_request = '9s'         # Primary send it to inform aliveness, must be greater than request timeout
    viewchange = '8s'           # How long may a view change take
    resend_viewchange = '10s'   # How long to wait for a view change quorum before resending (the same) view change
    clean_viewchange = '1m0s'   # How long to clean out-of-data view change message
    update = '4s'               # How long may a update-n take