{
 "title": "AxiomLedger",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "nodes",
    "query": {
     "query": "label_values(axiom_ledger_executor_apply_transactions_duration_seconds_count{job=\"local\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(axiom_ledger_executor_tx_counter{instance=~\"$nodes\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "rbft_status_normal{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Txpool tranaction count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "txpool_tx_counter{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transaction count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "axiom_ledger_executor_tx_counter{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "axiom_ledger_ledger_block_height{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Proposed block number",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axiom_ledger_executor_proposed_block_counter{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Persist block avg latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(axiom_ledger_ledger_persist_block_duration_second_sum{instance=~\"$nodes\"}[1m]) / rate(axiom_ledger_ledger_persist_block_duration_second_count{instance=~\"$nodes\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Apply EVM avg latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(axiom_ledger_executor_execute_block_duration_second_sum{instance=~\"$nodes\"}[1m]) / rate(axiom_ledger_executor_execute_block_duration_second_count{instance=~\"$nodes\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus process event avg latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(rbft_process_event_duration_sum{instance=~\"$nodes\", event=\"consensus_message\"}[1m]) / rate(rbft_process_event_duration_count{instance=~\"$nodes\", event=\"consensus_message\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Account cache miss count per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "axiom_ledger_ledger_account_cache_miss_counter_per_block{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV cache miss count per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "axiom_ledger_storage_kv_cache_miss_counter_per_block{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Account read avg latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(axiom_ledger_ledger_account_read_duration_sum{instance=~\"$nodes\"}[1m]) / rate(axiom_ledger_ledger_account_read_duration_count{instance=~\"$nodes\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Account cache hit count per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "axiom_ledger_ledger_account_cache_hit_counter_per_block{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KV cache hit count per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "axiom_ledger_storage_kv_cache_hit_counter_per_block{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "State read avg latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(axiom_ledger_ledger_state_read_duration_sum{instance=~\"$nodes\"}[1m]) / rate(axiom_ledger_ledger_state_read_duration_count{instance=~\"$nodes\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Txpool ready tranaction count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "txpool_ready_tx_counter{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Txpool rejected local tranaction count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "rbft_rejected_local_txs{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Txpool rejected remote tranaction count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "rbft_rejected_remote_txs{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Persist block latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(axiom_ledger_ledger_persist_block_duration_second_bucket{instance=~\"$nodes\"}[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Apply EVM latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(axiom_ledger_executor_execute_block_duration_second_bucket{instance=~\"$nodes\"}[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus process event latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(rbft_process_event_duration_bucket{instance=~\"$nodes\", event=\"consensus_message\"}[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gossipsub duplicate msg count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "gossipsub_duplicate_msg_counter{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gossipsub rejected msg count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "targets": [
    {
     "expr": "gossipsub_rejected_msg_counter{instance=~\"$nodes\", reason=\"all\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gossipsub undeliverable msg count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "targets": [
    {
     "expr": "gossipsub_undeliverable_msg_counter{instance=~\"$nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}